name: Deploy to Google Container Registry
description: A GitHub Action that deploys a Docker image to Google Container Registry

author: castroneto
branding:
  icon: archive
  color: blue

inputs:
  credentials_json:
    description: 'The JSON contents of the Google Cloud Service Account key file'
    required: true
  gcp_project:
    description: 'The name of the Google Cloud project'
    required: true
  gcp_registry:
    description: 'The URL of the Google Container Registry'
    required: true
  gcp_repository:
    description: 'The name of the Google Container Registry repository'
    required: true
  image_name:
    description: 'The name of the Docker image'
    required: true
  image_tag:
    description: 'The tag of the Docker image'
    required: true

outputs:
  image_uri:
    description: 'The URI of the Docker image in Google Container Registry'
    value: ${{ steps.push.outputs.image_uri }}

runs:
  using: 'node12'
  main: 'src/main.js'